# Generated by Django 5.2.15 on 2026-07-03 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand_or_shop_name', models.CharField(blank=True, max_length=120)),
                ('product_url', models.URLField(blank=True, max_length=1000)),
                ('normalized_url', models.CharField(blank=True, db_index=True, max_length=1000)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('price_text', models.CharField(blank=True, max_length=100)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('external_review_count', models.PositiveIntegerField(blank=True, null=True)),
                ('recommend_count', models.PositiveIntegerField(default=0)),
                ('disrecommend_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['-recommend_count', '-created_at'], name='common_item_recomme_9e62a0_idx'), models.Index(fields=['name'], name='common_item_name_b1e89f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ItemReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('recommend', '추천'), ('disrecommend', '비추천')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='common.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['item', 'reaction'], name='common_item_item_id_fd6b5d_idx'), models.Index(fields=['user', 'reaction'], name='common_item_user_id_216898_idx')],
                'constraints': [models.UniqueConstraint(fields=('item', 'user'), name='unique_item_reaction_per_user')],
            },
        ),
    ]
