# Generated by Django 5.2.15 on 2026-07-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('fashion', '의류/패션'), ('food', '식품'), ('beauty', '뷰티'), ('electronics', '전자제품'), ('appliances', '가전제품'), ('living', '생활용품'), ('health', '건강'), ('sports', '스포츠/레저'), ('books_hobby', '도서/취미'), ('kids_pets', '유아/반려동물'), ('etc', '기타')], db_index=True, default='etc', max_length=30),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category', '-recommend_count', '-created_at'], name='common_item_categor_1f5c3a_idx'),
        ),
    ]
