# Generated by Django 4.2.30 on 2026-07-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
    ]
