# Generated by Django 4.2.30 on 2026-07-04 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rebuild_review_foreign_keys'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_item_id_2bddfc_idx',
            old_name='reviews_rev_item_id_251ba0_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_author__8385c0_idx',
            old_name='reviews_rev_author__7c13ab_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_like_co_7aea26_idx',
            old_name='reviews_rev_like_co_3de2f7_idx',
        ),
        migrations.RenameIndex(
            model_name='reviewcomment',
            new_name='reviews_rev_review__b63a48_idx',
            old_name='reviews_rev_review__bb8a1c_idx',
        ),
        migrations.RenameIndex(
            model_name='reviewcomment',
            new_name='reviews_rev_author__b778a1_idx',
            old_name='reviews_rev_author__96883a_idx',
        ),
        migrations.RenameIndex(
            model_name='reviewcomment',
            new_name='reviews_rev_like_co_8294a4_idx',
            old_name='reviews_rev_like_co_a911da_idx',
        ),
    ]
