# Generated by Django 4.2.30 on 2026-07-04 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('fashion', '의류/패션'), ('food', '식품'), ('beauty', '뷰티'), ('electronics', '전자제품'), ('appliances', '가전제품'), ('living', '생활용품'), ('health', '건강'), ('sports', '스포츠/레저'), ('books_hobby', '도서/취미'), ('kids_pets', '유아/반려동물'), ('etc', '기타')], db_index=True, default='etc', max_length=30)),
                ('image_url', models.URLField(blank=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('price', models.PositiveIntegerField()),
                ('shop_or_brand_name', models.CharField(max_length=255)),
                ('original_url', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='star',
            constraint=models.UniqueConstraint(fields=('user', 'item'), name='unique_user_item_star'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name'], name='items_item_name_1c746e_idx'),
        ),
    ]
