# Generated by Django 5.2.15 on 2026-07-03 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_itemreaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('fashion', '의류/패션'), ('food', '식품'), ('beauty', '뷰티'), ('electronics', '전자제품'), ('appliances', '가전제품'), ('living', '생활용품'), ('health', '건강'), ('sports', '스포츠/레저'), ('books_hobby', '도서/취미'), ('kids_pets', '유아/반려동물'), ('etc', '기타')], db_index=True, default='etc', max_length=30),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['-recommend_count', '-created_at'], name='items_item_recomme_c8c8f5_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category', '-recommend_count', '-created_at'], name='items_item_categor_c3d8aa_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name'], name='items_item_name_1c746e_idx'),
        ),
    ]
