# Generated by Django 4.2.30 on 2026-07-04 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_image_file'),
        ('items', '0005_star_star_unique_user_item_star'),
    ]

    operations = [
    ]
